### ISSUE TITLE
Unsubscribe functionality missing?

### ISSUE THREAD

**Issue by ngjermundshaug** [eXpl0it3r/PubBus#1]
How to unsubscribe?

Are we missing a **MessageBus::Unsubscribe(SubscriberHandle)** method ?

**Comment by eXpl0it3r** [comment]
Looks like I never got around to implement it, but you've motivated me to fix this and update a few things. Interestingly enough, the `MessageContainer` already has a `remove()` function.

**Comment by eXpl0it3r** [comment]
@ngjermundshaug took a while with some additional clean up work, but you can now finally unsubscribe handles.
